---
version: "3.8"
services:
  # Create docker-compose file, which could be used to run integration tests for this project

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mailcatcher:
    image: "tophfr/mailcatcher:latest"
    ports:
      - "80:80"
      - "25:25"




